spring:
  application:
    name: auth

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/auth?authSource=admin

server:
  port: 8081

jwt:
  secret:   "my-super-secret-key-my-super-secret-key-123456"
  expiration: 86400000